openapi: 3.1.0
info:
  title: Photogether
  description: ''
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://photogether.store/api
    description: Production server
tags:
  - name: 인증
  - name: 사용자
  - name: 카테고리
  - name: 관심 카테고리
  - name: 사진첩
  - name: 게시물정보
paths:
  /v1/auth/login:
    post:
      summary: 로그인
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 패스워드
              required:
                - email
                - password
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  expiresIn:
                    type: integer
                required:
                  - accessToken
                  - refreshToken
                  - expiresIn
              examples:
                '1':
                  summary: Success
                  value:
                    accessToken: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5MjcyOTEsImV4cCI6MTc0MDAxMzY5MSwic3ViIjoiMSJ9.QlY-8RfkvLHwDgKWmVoxtNeyy6TyntyX4dm_a_urRzE
                    refreshToken: 5116973f-6464-4af8-817b-2876b999b3ec
                    expiresIn: 1740013691
          headers: {}
      security: []
  /v1/auth/register:
    post:
      summary: 회원가입
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 패스워드
              required:
                - email
                - password
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /v1/auth/otp/generate:
    post:
      summary: OTP 발급, 이메일 발송
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
              required:
                - email
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /v1/auth/otp/verify:
    post:
      summary: OTP 검증, 토큰 발급
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                otp:
                  type: string
                  description: OTP
              required:
                - email
                - otp
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  expiresIn:
                    type: integer
                required:
                  - accessToken
                  - refreshToken
                  - expiresIn
              examples:
                '1':
                  summary: Success
                  value:
                    accessToken: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5MjcyNjIsImV4cCI6MTc0MDAxMzY2Miwic3ViIjoiMSJ9.BEPVfYov_kirPvbeKEHk90htMXawqw4Javp89Mr99rU
                    refreshToken: f276fa99-9425-4c52-bc6f-c0c2b919f917
                    expiresIn: 1740013662
          headers: {}
      security: []
  /v1/auth/refresh:
    post:
      summary: 토큰 재발급
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters:
        - name: x-refresh-token
          in: header
          description: 리프레시토큰
          required: false
          example: 8f41fd40-4130-4921-950a-8851d1cbe598
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                  expiresIn:
                    type: integer
                required:
                  - accessToken
                  - refreshToken
                  - expiresIn
              examples:
                '1':
                  summary: Success
                  value:
                    accessToken: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5MzE1OTYsImV4cCI6MTc0MDAxNzk5Niwic3ViIjoiMSJ9.p02-OEtowYRTjZxUqjtHWChGC-Y6ja4dT37nVjJ2Uh0
                    refreshToken: bb28c242-d18e-4fc3-a330-5c0b093d87ba
                    expiresIn: 1740017996
          headers: {}
      security: []
  /v1/auth/logout:
    delete:
      summary: 로그아웃
      deprecated: false
      description: ''
      tags:
        - 인증
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/users/emails/{email}/duplicated:
    get:
      summary: 이메일 중복 검증
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters:
        - name: email
          in: path
          description: 이메일
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  isDuplicated:
                    type: boolean
                required:
                  - isDuplicated
              examples:
                '1':
                  summary: Success
                  value:
                    isDuplicated: true
          headers: {}
      security: []
  /v1/users/me:
    get:
      summary: 프로필 조회
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nickname:
                    type: string
                  bio:
                    type: string
                  email:
                    type: string
                  imageUrl:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                required:
                  - id
                  - nickname
                  - bio
                  - email
                  - imageUrl
                  - createdAt
                  - updatedAt
              examples:
                '1':
                  summary: Success
                  value:
                    id: 1
                    nickname: 든든한고래밥
                    bio: 자기소개
                    email: dev.goraebap@gmail.com
                    imageUrl: >-
                      https://storage.googleapis.com/photogether-d3c95.firebasestorage.app/2025%2F02%2F19%2Ffhhp8a7o4u73304zae3jhq0w.jpg
                    createdAt: '2025-02-19T04:48:46.718+00:00'
                    updatedAt: '2025-02-19T11:44:30.343+00:00'
          headers: {}
      security:
        - bearer: []
    put:
      summary: 프로필 수정
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nickname:
                  description: 닉네임
                  example: ''
                  type: string
                bio:
                  description: 자기소개
                  example: ''
                  type: string
                categoryIds:
                  type: string
                  deprecated: true
                  description: 카테고리 ID 목록 (문자열), 더이상 사용되지 않습니다.
                  example: ''
                file:
                  format: binary
                  type: string
                  description: 이미지 파일
                  example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nickname:
                    type: string
                  bio:
                    type: string
                  email:
                    type: string
                  imageUrl:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                required:
                  - id
                  - nickname
                  - bio
                  - email
                  - imageUrl
                  - createdAt
                  - updatedAt
              examples:
                '1':
                  summary: Success
                  value:
                    id: 1
                    nickname: 든든한고래밥
                    bio: 자기소개
                    email: dev.goraebap@gmail.com
                    imageUrl: >-
                      https://storage.googleapis.com/photogether-d3c95.firebasestorage.app/2025%2F02%2F19%2Fjt76awic9t9hv6stb10ov67u.jpg
                    createdAt: '2025-02-19T04:48:46.718+00:00'
                    updatedAt: '2025-02-19T11:50:02.599+00:00'
          headers: {}
      security:
        - bearer: []
  /v1/users/password:
    patch:
      summary: OTP인증 후 비밀번호 변경
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: OTP
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
              required:
                - otp
                - email
                - password
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /v1/users/me/password:
    patch:
      summary: 비밀번호 변경
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                  description: 현재 비밀번호
                newPassword:
                  type: string
                  description: 새로운 비밀번호
              required:
                - currentPassword
                - newPassword
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/users/me/reset:
    delete:
      summary: OTP 인증 후 기록 초기화
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: OTP
              required:
                - otp
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/users/me/withdraw:
    delete:
      summary: OTP 인증 후 회원 탈퇴
      deprecated: false
      description: ''
      tags:
        - 사용자
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: OTP
              required:
                - otp
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/categories:
    get:
      summary: 전체 카테고리 목록 조회
      deprecated: false
      description: ''
      tags:
        - 카테고리
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    createdAt:
                      type: string
                    updatedAt:
                      type: string
                  required:
                    - id
                    - name
                    - createdAt
                    - updatedAt
              examples:
                '1':
                  summary: Success
                  value:
                    - id: 1001
                      name: 기술
                      createdAt: '2025-02-19T03:56:27.627+00:00'
                      updatedAt: '2025-02-19T03:56:27.627+00:00'
                    - id: 1002
                      name: 건강 & 웰니스
                      createdAt: '2025-02-19T03:56:27.638+00:00'
                      updatedAt: '2025-02-19T03:56:27.638+00:00'
                    - id: 1003
                      name: 여행
                      createdAt: '2025-02-19T03:56:27.649+00:00'
                      updatedAt: '2025-02-19T03:56:27.649+00:00'
                    - id: 1004
                      name: 금융
                      createdAt: '2025-02-19T03:56:27.659+00:00'
                      updatedAt: '2025-02-19T03:56:27.659+00:00'
                    - id: 1005
                      name: 음식 & 요리
                      createdAt: '2025-02-19T03:56:27.669+00:00'
                      updatedAt: '2025-02-19T03:56:27.669+00:00'
                    - id: 1006
                      name: 엔터테인먼트
                      createdAt: '2025-02-19T03:56:27.681+00:00'
                      updatedAt: '2025-02-19T03:56:27.681+00:00'
                    - id: 1007
                      name: 교육
                      createdAt: '2025-02-19T03:56:27.692+00:00'
                      updatedAt: '2025-02-19T03:56:27.692+00:00'
                    - id: 1008
                      name: 스포츠
                      createdAt: '2025-02-19T03:56:27.703+00:00'
                      updatedAt: '2025-02-19T03:56:27.703+00:00'
                    - id: 1009
                      name: 비즈니스
                      createdAt: '2025-02-19T03:56:27.714+00:00'
                      updatedAt: '2025-02-19T03:56:27.714+00:00'
                    - id: 1010
                      name: 라이프스타일
                      createdAt: '2025-02-19T03:56:27.726+00:00'
                      updatedAt: '2025-02-19T03:56:27.726+00:00'
          headers: {}
      security: []
    post:
      summary: 카테고리 생성 (테스트, 관리자용)​
      deprecated: true
      description: ''
      tags:
        - 카테고리
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /v1/categories/with-favorite-status:
    get:
      summary: 전체 카테고리 별 관심사 여부 조회
      deprecated: false
      description: ''
      tags:
        - 카테고리
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    isFavorite:
                      type: boolean
                  required:
                    - id
                    - name
                    - isFavorite
              examples:
                '1':
                  summary: Success
                  value:
                    - id: 1001
                      name: 기술
                      isFavorite: false
                    - id: 1002
                      name: 건강 & 웰니스
                      isFavorite: false
                    - id: 1003
                      name: 여행
                      isFavorite: false
                    - id: 1004
                      name: 금융
                      isFavorite: false
                    - id: 1005
                      name: 음식 & 요리
                      isFavorite: false
                    - id: 1006
                      name: 엔터테인먼트
                      isFavorite: false
                    - id: 1007
                      name: 교육
                      isFavorite: false
                    - id: 1008
                      name: 스포츠
                      isFavorite: false
                    - id: 1009
                      name: 비즈니스
                      isFavorite: false
                    - id: 1010
                      name: 라이프스타일
                      isFavorite: false
          headers: {}
      security:
        - bearer: []
  /v1/categories/{categoryId}:
    delete:
      summary: 카테고리 삭제 (테스트, 관리자용)​
      deprecated: true
      description: ''
      tags:
        - 카테고리
      parameters:
        - name: categoryId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /v1/favorites:
    get:
      summary: 관심있는 카테고리 목록 조회
      deprecated: false
      description: |-
        고려해야할 상황)
        - 카테고리를 사용하는 사진첩이 존재하면 해당 카테고리는 삭제 할 수 없습니다.
        ex) 사진첩1이 '운동' 이라는 카테고리를 사용중이면 '운동' 카테고리를 삭제할 수 없습니다.
      tags:
        - 관심 카테고리
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    createdAt:
                      type: string
                    updatedAt:
                      type: string
                  required:
                    - id
                    - name
                    - createdAt
                    - updatedAt
              examples:
                '1':
                  summary: Success
                  value:
                    - id: 1001
                      name: 기술
                      createdAt: '2025-02-19T03:56:27.627+00:00'
                      updatedAt: '2025-02-19T03:56:27.627+00:00'
                    - id: 1002
                      name: 건강 & 웰니스
                      createdAt: '2025-02-19T03:56:27.638+00:00'
                      updatedAt: '2025-02-19T03:56:27.638+00:00'
                    - id: 1003
                      name: 여행
                      createdAt: '2025-02-19T03:56:27.649+00:00'
                      updatedAt: '2025-02-19T03:56:27.649+00:00'
          headers: {}
      security:
        - bearer: []
    put:
      summary: 관심 카테고리 그룹 생성/변경
      deprecated: false
      description: ''
      tags:
        - 관심 카테고리
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categoryIds:
                  type: array
                  items:
                    type: integer
                  minItems: 3
                  description: 카테고리ID 목록
              required:
                - categoryIds
            examples:
              '1':
                value:
                  categoryIds:
                    - 1001
                    - 1002
                    - 1003
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/collections:
    get:
      summary: 사진첩 목록 조회
      deprecated: false
      description: ''
      tags:
        - 사진첩
      parameters:
        - name: page
          in: query
          description: 페이지 번호
          required: false
          example: 1
          schema:
            type: integer
        - name: perPage
          in: query
          description: 한 페이지에 불러올 아이템 개수
          required: false
          example: 10
          schema:
            type: integer
        - name: sortOrder
          in: query
          description: 정렬방식
          required: false
          example: asc | desc
          schema:
            type: string
        - name: sortBy
          in: query
          description: 정렬대상
          required: false
          example: title | created_at
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  perPage:
                    type: integer
                  totalItemCount:
                    type: integer
                  totalPageCount:
                    type: integer
                  currentPage:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        type:
                          type: string
                        category:
                          type:
                            - object
                            - 'null'
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            createdAt:
                              type: string
                            updatedAt:
                              type: string
                          required:
                            - id
                            - name
                            - createdAt
                            - updatedAt
                        postCount:
                          type: integer
                        imageUrls:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
                        updatedAt:
                          type: string
                        userId:
                          type: integer
                        categoryId:
                          type:
                            - integer
                            - 'null'
                      required:
                        - id
                        - title
                        - type
                        - category
                        - postCount
                        - imageUrls
                        - createdAt
                        - updatedAt
                        - userId
                        - categoryId
                required:
                  - perPage
                  - totalItemCount
                  - totalPageCount
                  - currentPage
                  - items
              examples:
                '1':
                  summary: Success
                  value:
                    perPage: 10
                    totalItemCount: 3
                    totalPageCount: 1
                    currentPage: 1
                    items:
                      - id: 3
                        title: when entice cleave bitterly birdbath phew
                        type: DEFAULT
                        category:
                          id: 1001
                          name: 기술
                        postCount: 0
                        imageUrls: []
                        createdAt: '2025-02-19T06:06:06.043+00:00'
                        updatedAt: '2025-02-19T06:10:45.535+00:00'
                      - id: 2
                        title: 휴지통
                        type: TRASH
                        category: null
                        postCount: 3
                        imageUrls:
                          - >-
                            https://storage.googleapis.com/photogether-d3c95.firebasestorage.app/2025%2F02%2F20%2Fcq4nfir4xiearvuymgm8mpr2.jpg
                          - >-
                            https://storage.googleapis.com/photogether-d3c95.firebasestorage.app/2025%2F02%2F19%2Fzfvsfisti8xx3yehjek7q018.jpg
                        createdAt: '2025-02-19T04:48:46.825+00:00'
                        updatedAt: '2025-02-19T04:48:46.825+00:00'
                      - id: 1
                        title: 미분류
                        type: UNCATEGORIZED
                        category: null
                        postCount: 0
                        imageUrls: []
                        createdAt: '2025-02-19T04:48:46.811+00:00'
                        updatedAt: '2025-02-19T04:48:46.811+00:00'
          headers: {}
      security:
        - bearer: []
    post:
      summary: 사진첩 생성
      deprecated: false
      description: ''
      tags:
        - 사진첩
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                categoryId:
                  type: integer
                  description: 카테고리ID
              required:
                - title
                - categoryId
            examples:
              '1':
                value:
                  title: evil putrid until for break
                  categoryId: 1001
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/collections/{collectionId}:
    get:
      summary: 사진첩 상세 조회
      deprecated: false
      description: ''
      tags:
        - 사진첩
      parameters:
        - name: collectionId
          in: path
          description: 사진첩ID
          required: true
          example: '3'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                  category:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                    required:
                      - id
                      - name
                      - createdAt
                      - updatedAt
                  postCount:
                    type: 'null'
                  imageUrls:
                    type: array
                    items:
                      type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
                  userId:
                    type: integer
                  categoryId:
                    type: integer
                required:
                  - id
                  - title
                  - type
                  - category
                  - postCount
                  - imageUrls
                  - createdAt
                  - updatedAt
                  - userId
                  - categoryId
              examples:
                '1':
                  summary: Success
                  value:
                    id: 3
                    title: when entice cleave bitterly birdbath phew
                    type: DEFAULT
                    category:
                      id: 1001
                      name: 기술
                    postCount: null
                    imageUrls: []
                    createdAt: '2025-02-19T06:06:06.043+00:00'
                    updatedAt: '2025-02-19T06:10:45.535+00:00'
          headers: {}
      security:
        - bearer: []
    put:
      summary: 사진첩 수정
      deprecated: false
      description: ''
      tags:
        - 사진첩
      parameters:
        - name: collectionId
          in: path
          description: 사진첩ID
          required: true
          example: '3'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                categoryId:
                  type: integer
                  description: 카테고리 ID
              required:
                - title
                - categoryId
            examples:
              '1':
                value:
                  title: coolly yeast overvalue ha improbable
                  categoryId: 1001
                description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    delete:
      summary: 사진첩 삭제
      deprecated: false
      description: |-
        - 기본으로 제공되는 사진첩들은 삭제가 불가능합니다. (미분류, 휴지통)
        - 사진첩 삭제시 내부 게시물들은 사용자의 휴지통으로 이동됩니다.
      tags:
        - 사진첩
      parameters:
        - name: collectionId
          in: path
          description: 사진첩ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/posts:
    get:
      summary: 게시물 목록 조회
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters:
        - name: page
          in: query
          description: 페이지 번호
          required: false
          example: 1
          schema:
            type: integer
        - name: perPage
          in: query
          description: 한 페이지에 불러올 아이템 개수
          required: false
          example: 10
          schema:
            type: integer
        - name: sortOrder
          in: query
          description: 정렬방식
          required: false
          example: asc | desc
          schema:
            type: string
        - name: sortBy
          in: query
          description: 정렬대상
          required: false
          example: created_at
          schema:
            type: string
        - name: collectionId
          in: query
          description: collectionId
          required: false
          example: '123'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  perPage:
                    type: integer
                  totalItemCount:
                    type: integer
                  totalPageCount:
                    type: integer
                  currentPage:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        imageUrl:
                          type: 'null'
                        collectionId:
                          type: integer
                        collection:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                          required:
                            - id
                            - title
                        category:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            createdAt:
                              type: string
                            updatedAt:
                              type: string
                          required:
                            - id
                            - name
                            - createdAt
                            - updatedAt
                        metadataList:
                          type: array
                          items:
                            type: object
                            properties:
                              content:
                                type: string
                              isPublic:
                                type: boolean
                            required:
                              - content
                              - isPublic
                required:
                  - perPage
                  - totalItemCount
                  - totalPageCount
                  - currentPage
                  - items
              examples:
                '1':
                  summary: Success
                  value:
                    perPage: 10
                    totalItemCount: 1
                    totalPageCount: 1
                    currentPage: 1
                    items:
                      - id: 1
                        title: 제목입니다
                        content: sodyddlqslek
                        imageUrl: null
                        collectionId: 3
                        collection:
                          id: 3
                          title: when entice cleave bitterly birdbath phew
                        category:
                          id: 1001
                          name: 기술
                          createdAt: '2025-02-19T03:56:27.627+00:00'
                          updatedAt: '2025-02-19T03:56:27.627+00:00'
                        metadataList:
                          - content: hello
                            isPublic: true
                          - content: world
                            isPublic: true
          headers: {}
      security:
        - bearer: []
    post:
      summary: 게시물 생성
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                collectionId:
                  type: integer
                  description: 사진첩 ID
                  example: 3
                title:
                  description: 제목
                  example: 제목입니다
                  type: string
                content:
                  description: 내용
                  example: sodyddlqslek
                  type: string
                metadataStringify:
                  type: string
                  description: 매타데이터 json.stringify 형식. example 참고 필수
                  example: >-
                    [{"content":"hello","isPublic":true, "hasLink": false},{"content":"world","isPublic":true, "hasLink": true}]
                file:
                  format: binary
                  type: string
                  description: 이미지 파일
                  example: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    delete:
      summary: 게시물 그룹 삭제
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postIds:
                  type: array
                  items:
                    type: integer
                  description: 게시물 ID 그룹
              required:
                - postIds
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/posts/{postId}:
    put:
      summary: 게시물 수정
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters:
        - name: postId
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 제목
                content:
                  type: string
                  description: 내용
                metadataList:
                  type: array
                  items:
                    type: object
                    properties:
                      content:
                        type: string
                        description: 메타데이터 텍스트
                      isPublic:
                        type: boolean
                        description: 공개여부
                      hasLink:
                        type: boolean
                        description: 링크여부
                    required:
                      - content
                      - isPublic
                  description: 메타데이터 목록
              required:
                - postId
                - title
                - content
                - metadataList
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
    get:
      summary: 게시물 상세 조회
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters:
        - name: postId
          in: path
          description: 게시물ID
          required: true
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                  imageUrl:
                    type: string
                  collectionId:
                    type: integer
                  collection:
                    type: object
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                    required:
                      - id
                      - title
                  category:
                    type: 'null'
                  metadataList:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                        isPublic:
                          type: boolean
                      required:
                        - content
                        - isPublic
                required:
                  - id
                  - title
                  - content
                  - imageUrl
                  - collectionId
                  - collection
                  - category
                  - metadataList
              examples:
                '1':
                  summary: Success
                  value:
                    id: 3
                    title: zowie jive over
                    content: Sunt catena comminor
                    imageUrl: >-
                      https://storage.googleapis.com/photogether-d3c95.firebasestorage.app/2025%2F02%2F20%2Fcq4nfir4xiearvuymgm8mpr2.jpg
                    collectionId: 2
                    collection:
                      id: 2
                      title: 휴지통
                    category: null
                    metadataList:
                      - content: Tremo demum quia atrocitas vero soluta vomer.
                        isPublic: true
                      - content: 다라라라랄람
                        isPublic: true
          headers: {}
      security:
        - bearer: []
  /v1/posts/move:
    patch:
      summary: 게시물 그룹 다른 사진첩으로 이동
      deprecated: false
      description: ''
      tags:
        - 게시물정보
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postIds:
                  type: array
                  items:
                    type: integer
                  description: 게시물ID 목록
                collectionId:
                  type: integer
                  description: 사진첩 ID
              required:
                - collectionId
                - postIds
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security:
        - bearer: []
  /v1/images/preview:
    post:
      summary: 이미지 텍스트 미리보기
      description: 이미지에서 텍스트를 추출하여 줄 단위 배열(string[])로 반환합니다.
      tags:
        - 이미지
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 업로드할 이미지 파일
              required:
                - file
      responses:
        '200':
          description: 추출된 텍스트 배열
          content:
            application/json:
              schema:
                type: object
                properties:
                  lines:
                    type: array
                    items:
                      type: string
              examples:
                '1':
                  summary: Success
                  value:
                    lines:
                      - 무설탕
                      - Point.
                      - √ 1일,
                      - 3.5kcal
                      - 샤인머스켓
                      - 자일리톨 함량
                      - 98% 이상
                      - (핀란드산 100% 자일리톨)
                      - 천연향료 사용
                      - (콜라와 샤인머스켓은 원료 특성상 합성향료 사용)
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
